name: Django CI Pipeline â€” Tests & Coverage
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}


jobs:
  build_and_push:
    name: Django CI + Docker
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Recreate firebase admin credentials
        run: |
          set -e
          mkdir -p secrets
          echo "${{ secrets.FIREBASE_ADMIN_CREDENTIALS }}" | base64 --decode > secrets/rimayalertback-firebase-admin-sdk-key.json

      - name: Install system dependencies for GDAL and PostGIS
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable || true
          sudo apt-get update
          sudo apt-get install -y gdal-bin python3-gdal binutils libproj-dev
          gdalinfo --version || true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/production.txt

      - name: Set environment variables
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
          echo "POSTGRES_HOST=localhost" >> $GITHUB_ENV
          echo "POSTGRES_PORT=5432" >> $GITHUB_ENV
          echo "DEBUG=0" >> $GITHUB_ENV

      - name: Apply migrations
        run: python manage.py migrate

      - name: Run tests with coverage
        run: |
          coverage run manage.py test
          coverage xml

      - name: login to DockerHub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker build -f DockerfileProduction -t ${{ secrets.DOCKER_USERNAME }}/django-app:latest .

      - name: Push Docker image to DockerHub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/django-app:latest